=head1 NAME

Class::MakeMethods::Template::Changes - Revision history


=head1 SYNOPSIS

Revision history for Class::MakeMethods::Template.


=head1 CHANGES


=head2 v1.004

2002/02/07 Added missing *_reset => clear to number --counter interface.

2002/01/26 Documentation fix from Adam Spiers.


=head2 v1.003

2002/01/24 Split Template and Emulator packages into their own distributions.


=head1 SEE ALSO

L<Class::MakeMethods::Template::ReadMe>

=cut

